import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import { NavbarItem } from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const items: NavbarItem[] = ["首頁", "偉特介紹", "磁磚分類", "服務流程", "聯絡我們"];
  const navbarItems: NavbarItem[] = [
    {
      title: "首頁",
      to: "/",
    },
    {
      title: "偉特介紹",
      to: "/introduction",
    },
    {
      title: "磁磚分類",
      to: "/category",
    },
    {
      title: "服務流程",
      to: "/service",
    },
    {
      title: "聯絡我們",
      to: "/contact",
    },
  ];

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar items={navbarItems} />
        {children}
      </body>
    </html>
  );
}
